<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
	<!-- parameter list -->
	<xacro:property name="gripper_length" value="0.0"/>
	<xacro:property name="gripper_width" value="0.0"/>
	<xacro:property name="gripper_height" value="0.0"/>

	<xacro:property name="asus_length" value="0.220"/>
	<xacro:property name="asus_width" value="0.040"/>
	<xacro:property name="asus_height" value="0.040"/>

	<xacro:macro name="blending_eff_definition" params="eff_adjustment">
		<link name="eff_frame"/>
		<link name="gripper_body">
			<visual>
				<geometry>
					<mesh filename="package://godel_robot_config/meshes/Deburring_eff.STL" />
				</geometry>
				<material name="silver">
					<color rgba="0.8 0.8 0.8 1"/>
				</material>
			</visual>
			<collision>
				<geometry>
					<mesh filename="package://godel_robot_config/meshes/Deburring_eff_Collision_Model.STL" />
				</geometry>
				<material name="another_blue2">
					<color rgba="0.38 0.54 0.83 1"/>
				</material>
			</collision>
		</link>
		<link name="tcp_frame"/>
		<joint name="gripper_to_palm" type="fixed">
			<parent link="eff_frame"/>
			<child link="gripper_body"/>
			<origin xyz="0 0 ${gripper_height * 0.5}" rpy="0 0 3.6651914"/>
		</joint>
		
		<link name="asus">
			<visual>
				<geometry>
					<box size="${asus_length} ${asus_width} ${asus_height}"/>
				</geometry>
				<material name="black"/>
			</visual>
			<collision>
				<geometry>
					<box size="${asus_length} ${asus_width} ${asus_height}"/>
				</geometry>
				<material name="another_blue2"/>
			</collision>
		</link>

		<joint name="eff_frame_to_asus" type="fixed">
			<parent link="eff_frame"/>
			<child link="asus"/>
			<origin xyz="0 0 0.150" rpy="0 0 3.6651914"/>
		</joint>

		<joint name="gripper_to_tcp" type="fixed">
			<parent link="eff_frame"/>
			<child link="tcp_frame"/>
			<origin xyz=" 0 ${gripper_length} ${eff_adjustment}" rpy="0 0 0"/>
		</joint>	
	</xacro:macro>
</robot>
