---
frame_id: world_frame
k_search: 20
umarker_alpha: 1.0
meanK: 1
stdv_threshold: 3

rg_min_cluster_size: 100
rg_max_cluster_size: 10000
rg_neighbors: 20
rg_smoothness_threshold: 4.5
rg_curvature_threshold: 2

voxel_leafsize: 0.005
tabletop_seg_distance_threshold: 0.005
use_tabletop_seg: false
ignore_largest_cluster: false

mls_point_density: 100
mls_upsampling_radius: 0.01
mls_search_radius: 0.04

tr_search_radius: 0.01
tr_mu: 2.5
tr_max_nearest_neighbors: 100
tr_max_surface_angle: 45
tr_min_angle: 10
tr_max_angle: 120
tr_normal_consistency: false

pa_enabled: true
pa_seg_max_iterations: 200
pa_seg_dist_threshold: 0.01
pa_sac_plane_distance: 0.01
pa_kdtree_radius: 0.01
...
